apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-rpm-
spec:
  pipelineRef:
    name: create-rpm
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
    - name: ssh-creds
      secret:
        secretName: tekton-ssh-credentials
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  params:
    - name: repo-url
      value: https://github.com/55octet/tekton-rpm.git
