apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rpm-build
spec:
  # resources:
  # outputs:
  # https://stackoverflow.com/questions/69617680/output-types-for-tekton-task
  # The docs do not mention the types; this SO literally pulled it from the src
  # - name: builtRpm
  #   type: storage
  # - name: builtSourceRpm
  #   type: storage
  workspaces:
    - name: source
  steps:
    - name: build
      image: centos:7
      script: |
        set -x on
        set -v on
        yum install -y rpmdevtools rpmlint
        cd $(workspaces.source.path)/rpmbuild
        tar czvf SOURCES/test-0.0.1.tar.gz test-0.0.1/
        rpmlint SPECS/test.spec
        rpmbuild -bs SPECS/test.spec
        rpmbuild -bb SPECS/test.spec
        mkdir -p $(workspaces.source.path)/rpms
        cp ~/rpmbuild/RPMS/noarch/*.rpm ~/rpmbuild/SRPMS/*.rpm $(workspaces.source.path)/rpms
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: create-rpm
spec:
  description: |
    This pipeline clones a git repo, then creates an rpm
  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from.
  workspaces:
    - name: shared-data
      description: |
        This workspace contains the cloned repo files, so they can be read by the
        next task.
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
    - name: rpm-build
      runAfter:
        - fetch-source
      taskRef:
        name: rpm-build
      workspaces:
        - name: source
          workspace: shared-data
