# This service account is used by the pod that listens for the webhooks
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-eventlistener
---
# These two RoleBindings ensure that the pod can look up the spec for the event listener
# and associated objects
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-eventlistener-binding
subjects:
  - kind: ServiceAccount
    name: tekton-eventlistener
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-eventlistener-binding
subjects:
  - kind: ServiceAccount
    name: tekton-eventlistener
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: bitbucket-refs-changed
spec:
  params:
    - name: event-key
      value: $(header.X-Event-Key)
    - name: request-id
      value: $(header.X-Request-Id)
    - name: body
      value: $(body)
    - name: committer-name
      value: $(body.actor.display_name)
    - name: pullrequest-id
      value: $(body.pullrequest.id)
    - name: pullrequest-author
      value: $(body.pullrequest.author.display_name)
    - name: pullrequest-nickname
      value: $(body.pullrequest.author.nickname)
    - name: pullrequest-url
      value: $(body.pullrequest.links.self.href)
    - name: pullrequest-api-comments
      value: $(body.pullrequest.links.comments.href)
---
# This listens for the actual webhook
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: bitbucket-cloud-listener
spec:
  serviceAccountName: tekton-eventlistener
  triggers:
    - name: bitbucket-server-triggers
      # Interceptors parse the webhook to scrape the data from the POST payload
      # There are ClusterInterceptors for GitLab, GitHub, and BitBucket
      # There is a generic ClusterInterceptor (CEL) that can be used to parse custom webhooks
      # https://tekton.dev/docs/triggers/clusterinterceptors/
      interceptors:
        - ref:
            name: "bitbucket"
          params:
            # This is required for a private instance of bitbucket
            # This example is using bitbucket cloud, so it does not support the secrets
            # - name: secretRef
            #   value:
            #     secretName: bitbucket-server-secret
            #     secretKey: secretToken
            - name: eventTypes
              value:
                # BitBucket repo eventTypes are here:
                # https://support.atlassian.com/bitbucket-cloud/docs/event-payloads/#Repository
                - repo:refs_changed
                - repo:push
                - pullrequest:created
                - pullrequest:updated
        - name: marshall-body
          ref:
            name: cel
          params:
            - name: overlays
              value:
                - key: webhook-payload
                  expression: body.marshalJSON()
        # - name: "Pull on main or Pull request"
        #   ref:
        #     name: cel
        #   params:
        #     - name: filter
        #       # This should allow only pushes to main or master and push request updates to trigger the pipeline
        #       value: >
        #         (has(body.pullrequest) && has(body.pullrequest.id)) ||
        #         (has(body.push) && has(body.push.changes) && body.push.changes.exists(x, x.old.type == "branch" && x.old.name in ['main','master']))

      # binding are the mechanism you use to pass the webhook parameters into the TaskRun/PipelineRun objects
      # https://tekton.dev/docs/triggers/triggerbindings/
      bindings:
        - ref: bitbucket-refs-changed
      template:
        spec:
          params:
            - name: body
              default: ""
            - name: repo-url
              default: "git@bitbucket.org:55octet/tekon-triggers.git"
            - name: event-key
            - name: request-id
            - name: committer-name
              default: No name
            # Pull Request Info
            - name: pullrequest-id
              default: ""
            - name: pullrequest-author
              default: ""
            - name: pullrequest-nickname
              default: ""
            - name: pullrequest-url
              default: ""
            - name: pullrequest-api-comments
              default: ""
          resourceTemplates:
            - apiVersion: tekton.dev/v1beta1
              kind: PipelineRun
              metadata:
                generateName: build-rpm-
              spec:
                pipelineRef:
                  name: create-rpm
                podTemplate:
                  securityContext:
                    fsGroup: 65532
                params:
                  - name: body
                    value: $(tt.params.extensions.webhook-payload)
                  - name: repo-url
                    value: $(tt.params.repo-url)
                  - name: event-key
                    value: $(tt.params.event-key)
                  - name: request-id
                    value: $(tt.params.request-id)
                  - name: committer-name
                    value: $(tt.params.committer-name)
                  - name: pullrequest-id
                    value: $(tt.params.pullrequest-id)
                  - name: pullrequest-author
                    value: $(tt.params.pullrequest-author)
                  - name: pullrequest-nickname
                    value: $(tt.params.pullrequest-nickname)
                  - name: pullrequest-url
                    value: $(tt.params.pullrequest-url)
                  - name: pullrequest-api-comments
                    value: $(tt.params.pullrequest-api-comments)
                workspaces:
                  - name: ssh-creds
                    secret:
                      secretName: tekton-ssh-credentials
                  - name: shared-data
                    volumeClaimTemplate:
                      spec:
                        accessModes:
                          - ReadWriteOnce
                        resources:
                          requests:
                            storage: 1Gi
---
# This is mainly for publicly-trusted certificate creation
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-tekton
spec:
  acme:
    email: djreynolds+acme@sei.cmu.edu
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-tekton-issuer-key
    solvers:
      - http01:
          ingress:
            ingressTemplate:
              metadata:
                annotations:
                  kubernetes.io/ingress.class: addon-http-application-routing
---
# Ingress class for AKS; can be replaced with an Openshift Route
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitbucket-listener
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    cert-manager.io/issuer: letsencrypt-tekton
spec:
  tls:
    - hosts:
        - bitbucket-listener.cd7198284aee45039778.centralus.aksapp.io
      secretName: bitbucket-listener-tls-secret
  rules:
    - host: bitbucket-listener.cd7198284aee45039778.centralus.aksapp.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: el-bitbucket-cloud-listener
                port:
                  number: 8080
